import { Hono } from 'hono';
import type { D1Database, R2Bucket } from '@cloudflare/workers-types';
import { getInbox, createInbox, inboxExists, getSessionInboxes, getMessages, ensureSession, linkInboxToSession, unlinkInboxFromSession, isInboxInSession, getAttachment, getMessage, getAdminStats, getAdminInboxes, getAdminMessages, deleteInbox, deleteMessage } from '../db/queries';
import { generateUniqueAddress } from '../utils/random-address';

export interface ApiEnv { DB: D1Database; ATTACHMENTS: R2Bucket; APP_NAME: string; MAIL_DOMAIN: string; WEB_HOST: string; EXPIRY_DAYS?: string; ADMIN_KEY?: string; }
function getDomains(env: ApiEnv): string[] { return env.MAIL_DOMAIN.split(',').map((d) => d.trim()).filter(Boolean); }
function defaultDomain(env: ApiEnv): string { return getDomains(env)[0] || 'example.com'; }
function sessionId(c: any): string | null { return (c.req.header('x-session-id') || c.req.query('session') || '').trim() || null; }
function requireSession(c: any): string { const sid = sessionId(c); if (!sid) { c.status(400); return ''; } return sid; }
function requireAdmin(c: any): boolean { const configured = c.env.ADMIN_KEY; const supplied = c.req.header('x-admin-key'); return !!configured && !!supplied && supplied === configured; }
function adminDenied(c: any) { return c.json({ error: 'Admin authentication required' }, 401); }
const api = new Hono<{ Bindings: ApiEnv }>();

api.get('/config', (c) => { const domains = getDomains(c.env); return c.json({ appName: 'RatioMail', mailDomain: domains[0] || 'example.com', mailDomains: domains, webHost: c.env.WEB_HOST || 'mail.ratiodevelopment.xyz', expiryDays: parseInt(c.env.EXPIRY_DAYS || '0', 10) }); });
api.get('/session', async (c) => { let sid = sessionId(c) || crypto.randomUUID(); await ensureSession(c.env.DB, sid); return c.json({ sessionId: sid }); });
api.get('/inboxes', async (c) => { const sid = requireSession(c); if (!sid) return c.json({ error: 'Missing x-session-id' }, 400); return c.json(await getSessionInboxes(c.env.DB, sid)); });
api.post('/inboxes', async (c) => { const sid = requireSession(c); if (!sid) return c.json({ error: 'Missing x-session-id' }, 400); const body = await c.req.json().catch(() => ({})); const domains = getDomains(c.env); const requestedDomain: string = (body.domain || '').trim().toLowerCase(); const domain = requestedDomain && domains.includes(requestedDomain) ? requestedDomain : defaultDomain(c.env); if (requestedDomain && !domains.includes(requestedDomain)) return c.json({ error: `Invalid domain: ${requestedDomain}. Allowed: ${domains.join(', ')}` }, 400); const requested: string = (body.localPart || '').trim().toLowerCase(); const address = requested ? `${requested}@${domain}` : await generateUniqueAddress((addr) => inboxExists(c.env.DB, addr), domain); await createInbox(c.env.DB, address); await linkInboxToSession(c.env.DB, sid, address); return c.json((await getInbox(c.env.DB, address))!, 201); });
api.delete('/inboxes/:address', async (c) => { const sid = requireSession(c); if (!sid) return c.json({ error: 'Missing x-session-id' }, 400); await unlinkInboxFromSession(c.env.DB, sid, decodeURIComponent(c.req.param('address'))); return c.json({ ok: true }); });
api.get('/inboxes/:address/messages', async (c) => { const sid = requireSession(c); if (!sid) return c.json({ error: 'Missing x-session-id' }, 400); const address = decodeURIComponent(c.req.param('address')); if (!(await isInboxInSession(c.env.DB, sid, address))) return c.json({ error: 'Inbox not in this session' }, 403); return c.json(await getMessages(c.env.DB, address)); });
api.get('/attachments/:attachmentId', async (c) => { const sid = requireSession(c); if (!sid) return c.json({ error: 'Missing session' }, 400); const attachment = await getAttachment(c.env.DB, c.req.param('attachmentId')); if (!attachment) return c.json({ error: 'Attachment not found' }, 404); const message = await getMessage(c.env.DB, attachment.message_id); if (!message || !(await isInboxInSession(c.env.DB, sid, message.inbox_address))) return c.json({ error: 'Forbidden' }, 403); const object = await c.env.ATTACHMENTS.get(attachment.object_key); if (!object) return c.json({ error: 'Attachment content not found' }, 404); const headers = new Headers(); object.writeHttpMetadata(headers); headers.set('Cache-Control', 'private, max-age=3600'); headers.set('X-Content-Type-Options', 'nosniff'); return new Response(object.body, { headers }); });
api.get('/admin/stats', async (c) => { if (!requireAdmin(c)) return adminDenied(c); return c.json(await getAdminStats(c.env.DB)); });
api.get('/admin/inboxes', async (c) => { if (!requireAdmin(c)) return adminDenied(c); return c.json(await getAdminInboxes(c.env.DB)); });
api.get('/admin/inboxes/:address/messages', async (c) => { if (!requireAdmin(c)) return adminDenied(c); return c.json(await getAdminMessages(c.env.DB, decodeURIComponent(c.req.param('address')))); });
api.delete('/admin/inboxes/:address', async (c) => { if (!requireAdmin(c)) return adminDenied(c); const attachments = await deleteInbox(c.env.DB, decodeURIComponent(c.req.param('address'))); await Promise.all(attachments.map((attachment) => c.env.ATTACHMENTS.delete(attachment.object_key))); return c.json({ ok: true, deletedAttachments: attachments.length }); });
api.delete('/admin/messages/:messageId', async (c) => { if (!requireAdmin(c)) return adminDenied(c); const attachments = await deleteMessage(c.env.DB, c.req.param('messageId')); await Promise.all(attachments.map((attachment) => c.env.ATTACHMENTS.delete(attachment.object_key))); return c.json({ ok: true, deletedAttachments: attachments.length }); });
export default api;
