import { Hono } from 'hono';
import type { D1Database } from '@cloudflare/workers-types';
import { getInbox,createInbox,inboxExists,getSessionInboxes,getMessages,ensureSession,linkInboxToSession,unlinkInboxFromSession,isInboxInSession } from '../db/queries';
import { generateUniqueAddress } from '../utils/random-address';
export interface ApiEnv { DB:D1Database; APP_NAME:string; MAIL_DOMAIN:string; WEB_HOST:string; EXPIRY_DAYS?:string; }
async function getDomains(env:ApiEnv):Promise<string[]> { const base=env.MAIL_DOMAIN.split(',').map(d=>d.trim().toLowerCase()).filter(Boolean); try { await env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_domains (domain TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run(); const rows=(await env.DB.prepare('SELECT domain FROM admin_domains WHERE enabled=1').all()).results as {domain:string}[]; return [...new Set([...base,...rows.map(r=>r.domain)])]; } catch { return base; } }
function sessionId(c:any):string|null{return(c.req.header('x-session-id')||'').trim()||null;}
function requireSession(c:any):string{const sid=sessionId(c);if(!sid)c.status(400);return sid||'';}
const api=new Hono<{Bindings:ApiEnv}>();
api.get('/config',async c=>{const domains=await getDomains(c.env);return c.json({appName:c.env.APP_NAME||'RatioMail',mailDomain:domains[0]||'example.com',mailDomains:domains,webHost:c.env.WEB_HOST||'mail.ratiodevelopment.xyz',expiryDays:parseInt(c.env.EXPIRY_DAYS||'0',10)});});
api.get('/session',async c=>{let sid=sessionId(c)||crypto.randomUUID();await ensureSession(c.env.DB,sid);return c.json({sessionId:sid});});
api.get('/inboxes',async c=>{const sid=requireSession(c);if(!sid)return c.json({error:'Missing x-session-id'},400);return c.json(await getSessionInboxes(c.env.DB,sid));});
api.post('/inboxes',async c=>{const sid=requireSession(c);if(!sid)return c.json({error:'Missing x-session-id'},400);const body=await c.req.json().catch(()=>({}));const domains=await getDomains(c.env);const requestedDomain=String(body.domain||'').trim().toLowerCase();const domain=requestedDomain&&domains.includes(requestedDomain)?requestedDomain:domains[0]||'example.com';if(requestedDomain&&!domains.includes(requestedDomain))return c.json({error:`Invalid domain: ${requestedDomain}. Allowed: ${domains.join(', ')}`},400);const requested=String(body.localPart||'').trim().toLowerCase();const address=requested?`${requested}@${domain}`:await generateUniqueAddress(a=>inboxExists(c.env.DB,a),domain);await createInbox(c.env.DB,address);await linkInboxToSession(c.env.DB,sid,address);return c.json((await getInbox(c.env.DB,address))!,201);});
api.delete('/inboxes/:address',async c=>{const sid=requireSession(c);if(!sid)return c.json({error:'Missing x-session-id'},400);await unlinkInboxFromSession(c.env.DB,sid,decodeURIComponent(c.req.param('address')));return c.json({ok:true});});
api.get('/inboxes/:address/messages',async c=>{const sid=requireSession(c);if(!sid)return c.json({error:'Missing x-session-id'},400);const address=decodeURIComponent(c.req.param('address'));if(!(await isInboxInSession(c.env.DB,sid,address)))return c.json({error:'Inbox not in this session'},403);return c.json(await getMessages(c.env.DB,address));});
export default api;
